// Complete Hiragana and Katakana character sets with learning structure

const hiragana = {
    basic: [
        { char: 'あ', romaji: 'a', type: 'vowel', group: 'a-row' },
        { char: 'い', romaji: 'i', type: 'vowel', group: 'a-row' },
        { char: 'う', romaji: 'u', type: 'vowel', group: 'a-row' },
        { char: 'え', romaji: 'e', type: 'vowel', group: 'a-row' },
        { char: 'お', romaji: 'o', type: 'vowel', group: 'a-row' },
    ],
    k: [
        { char: 'か', romaji: 'ka', type: 'consonant', group: 'k-row' },
        { char: 'き', romaji: 'ki', type: 'consonant', group: 'k-row' },
        { char: 'く', romaji: 'ku', type: 'consonant', group: 'k-row' },
        { char: 'け', romaji: 'ke', type: 'consonant', group: 'k-row' },
        { char: 'こ', romaji: 'ko', type: 'consonant', group: 'k-row' },
    ],
    s: [
        { char: 'さ', romaji: 'sa', type: 'consonant', group: 's-row' },
        { char: 'し', romaji: 'shi', type: 'consonant', group: 's-row' },
        { char: 'す', romaji: 'su', type: 'consonant', group: 's-row' },
        { char: 'せ', romaji: 'se', type: 'consonant', group: 's-row' },
        { char: 'そ', romaji: 'so', type: 'consonant', group: 's-row' },
    ],
    t: [
        { char: 'た', romaji: 'ta', type: 'consonant', group: 't-row' },
        { char: 'ち', romaji: 'chi', type: 'consonant', group: 't-row' },
        { char: 'つ', romaji: 'tsu', type: 'consonant', group: 't-row' },
        { char: 'て', romaji: 'te', type: 'consonant', group: 't-row' },
        { char: 'と', romaji: 'to', type: 'consonant', group: 't-row' },
    ],
    n: [
        { char: 'な', romaji: 'na', type: 'consonant', group: 'n-row' },
        { char: 'に', romaji: 'ni', type: 'consonant', group: 'n-row' },
        { char: 'ぬ', romaji: 'nu', type: 'consonant', group: 'n-row' },
        { char: 'ね', romaji: 'ne', type: 'consonant', group: 'n-row' },
        { char: 'の', romaji: 'no', type: 'consonant', group: 'n-row' },
    ],
    h: [
        { char: 'は', romaji: 'ha', type: 'consonant', group: 'h-row' },
        { char: 'ひ', romaji: 'hi', type: 'consonant', group: 'h-row' },
        { char: 'ふ', romaji: 'fu', type: 'consonant', group: 'h-row' },
        { char: 'へ', romaji: 'he', type: 'consonant', group: 'h-row' },
        { char: 'ほ', romaji: 'ho', type: 'consonant', group: 'h-row' },
    ],
    m: [
        { char: 'ま', romaji: 'ma', type: 'consonant', group: 'm-row' },
        { char: 'み', romaji: 'mi', type: 'consonant', group: 'm-row' },
        { char: 'む', romaji: 'mu', type: 'consonant', group: 'm-row' },
        { char: 'め', romaji: 'me', type: 'consonant', group: 'm-row' },
        { char: 'も', romaji: 'mo', type: 'consonant', group: 'm-row' },
    ],
    y: [
        { char: 'や', romaji: 'ya', type: 'consonant', group: 'y-row' },
        { char: 'ゆ', romaji: 'yu', type: 'consonant', group: 'y-row' },
        { char: 'よ', romaji: 'yo', type: 'consonant', group: 'y-row' },
    ],
    r: [
        { char: 'ら', romaji: 'ra', type: 'consonant', group: 'r-row' },
        { char: 'り', romaji: 'ri', type: 'consonant', group: 'r-row' },
        { char: 'る', romaji: 'ru', type: 'consonant', group: 'r-row' },
        { char: 'れ', romaji: 're', type: 'consonant', group: 'r-row' },
        { char: 'ろ', romaji: 'ro', type: 'consonant', group: 'r-row' },
    ],
    w: [
        { char: 'わ', romaji: 'wa', type: 'consonant', group: 'w-row' },
        { char: 'を', romaji: 'wo', type: 'consonant', group: 'w-row' },
    ],
    n: [
        { char: 'ん', romaji: 'n', type: 'special', group: 'n-special' },
    ],
    dakuten: [
        { char: 'が', romaji: 'ga', base: 'か', group: 'dakuten-k' },
        { char: 'ぎ', romaji: 'gi', base: 'き', group: 'dakuten-k' },
        { char: 'ぐ', romaji: 'gu', base: 'く', group: 'dakuten-k' },
        { char: 'げ', romaji: 'ge', base: 'け', group: 'dakuten-k' },
        { char: 'ご', romaji: 'go', base: 'こ', group: 'dakuten-k' },
        { char: 'ざ', romaji: 'za', base: 'さ', group: 'dakuten-s' },
        { char: 'じ', romaji: 'ji', base: 'し', group: 'dakuten-s' },
        { char: 'ず', romaji: 'zu', base: 'す', group: 'dakuten-s' },
        { char: 'ぜ', romaji: 'ze', base: 'せ', group: 'dakuten-s' },
        { char: 'ぞ', romaji: 'zo', base: 'そ', group: 'dakuten-s' },
        { char: 'だ', romaji: 'da', base: 'た', group: 'dakuten-t' },
        { char: 'ぢ', romaji: 'ji', base: 'ち', group: 'dakuten-t' },
        { char: 'づ', romaji: 'zu', base: 'つ', group: 'dakuten-t' },
        { char: 'で', romaji: 'de', base: 'て', group: 'dakuten-t' },
        { char: 'ど', romaji: 'do', base: 'と', group: 'dakuten-t' },
        { char: 'ば', romaji: 'ba', base: 'は', group: 'dakuten-h' },
        { char: 'び', romaji: 'bi', base: 'ひ', group: 'dakuten-h' },
        { char: 'ぶ', romaji: 'bu', base: 'ふ', group: 'dakuten-h' },
        { char: 'べ', romaji: 'be', base: 'へ', group: 'dakuten-h' },
        { char: 'ぼ', romaji: 'bo', base: 'ほ', group: 'dakuten-h' },
    ],
    handakuten: [
        { char: 'ぱ', romaji: 'pa', base: 'は', group: 'handakuten-h' },
        { char: 'ぴ', romaji: 'pi', base: 'ひ', group: 'handakuten-h' },
        { char: 'ぷ', romaji: 'pu', base: 'ふ', group: 'handakuten-h' },
        { char: 'ぺ', romaji: 'pe', base: 'へ', group: 'handakuten-h' },
        { char: 'ぽ', romaji: 'po', base: 'ほ', group: 'handakuten-h' },
    ],
    combo: [
        { char: 'きゃ', romaji: 'kya', base: 'き', group: 'combo-y' },
        { char: 'きゅ', romaji: 'kyu', base: 'き', group: 'combo-y' },
        { char: 'きょ', romaji: 'kyo', base: 'き', group: 'combo-y' },
        { char: 'しゃ', romaji: 'sha', base: 'し', group: 'combo-y' },
        { char: 'しゅ', romaji: 'shu', base: 'し', group: 'combo-y' },
        { char: 'しょ', romaji: 'sho', base: 'し', group: 'combo-y' },
        { char: 'ちゃ', romaji: 'cha', base: 'ち', group: 'combo-y' },
        { char: 'ちゅ', romaji: 'chu', base: 'ち', group: 'combo-y' },
        { char: 'ちょ', romaji: 'cho', base: 'ち', group: 'combo-y' },
        { char: 'にゃ', romaji: 'nya', base: 'に', group: 'combo-y' },
        { char: 'にゅ', romaji: 'nyu', base: 'に', group: 'combo-y' },
        { char: 'にょ', romaji: 'nyo', base: 'に', group: 'combo-y' },
        { char: 'ひゃ', romaji: 'hya', base: 'ひ', group: 'combo-y' },
        { char: 'ひゅ', romaji: 'hyu', base: 'ひ', group: 'combo-y' },
        { char: 'ひょ', romaji: 'hyo', base: 'ひ', group: 'combo-y' },
        { char: 'みゃ', romaji: 'mya', base: 'み', group: 'combo-y' },
        { char: 'みゅ', romaji: 'myu', base: 'み', group: 'combo-y' },
        { char: 'みょ', romaji: 'myo', base: 'み', group: 'combo-y' },
        { char: 'りゃ', romaji: 'rya', base: 'り', group: 'combo-y' },
        { char: 'りゅ', romaji: 'ryu', base: 'り', group: 'combo-y' },
        { char: 'りょ', romaji: 'ryo', base: 'り', group: 'combo-y' },
        { char: 'ぎゃ', romaji: 'gya', base: 'ぎ', group: 'combo-y' },
        { char: 'ぎゅ', romaji: 'gyu', base: 'ぎ', group: 'combo-y' },
        { char: 'ぎょ', romaji: 'gyo', base: 'ぎ', group: 'combo-y' },
        { char: 'じゃ', romaji: 'ja', base: 'じ', group: 'combo-y' },
        { char: 'じゅ', romaji: 'ju', base: 'じ', group: 'combo-y' },
        { char: 'じょ', romaji: 'jo', base: 'じ', group: 'combo-y' },
        { char: 'びゃ', romaji: 'bya', base: 'び', group: 'combo-y' },
        { char: 'びゅ', romaji: 'byu', base: 'び', group: 'combo-y' },
        { char: 'びょ', romaji: 'byo', base: 'び', group: 'combo-y' },
        { char: 'ぴゃ', romaji: 'pya', base: 'ぴ', group: 'combo-y' },
        { char: 'ぴゅ', romaji: 'pyu', base: 'ぴ', group: 'combo-y' },
        { char: 'ぴょ', romaji: 'pyo', base: 'ぴ', group: 'combo-y' },
    ],
};

const katakana = {
    basic: [
        { char: 'ア', romaji: 'a', type: 'vowel', group: 'a-row' },
        { char: 'イ', romaji: 'i', type: 'vowel', group: 'a-row' },
        { char: 'ウ', romaji: 'u', type: 'vowel', group: 'a-row' },
        { char: 'エ', romaji: 'e', type: 'vowel', group: 'a-row' },
        { char: 'オ', romaji: 'o', type: 'vowel', group: 'a-row' },
    ],
    k: [
        { char: 'カ', romaji: 'ka', type: 'consonant', group: 'k-row' },
        { char: 'キ', romaji: 'ki', type: 'consonant', group: 'k-row' },
        { char: 'ク', romaji: 'ku', type: 'consonant', group: 'k-row' },
        { char: 'ケ', romaji: 'ke', type: 'consonant', group: 'k-row' },
        { char: 'コ', romaji: 'ko', type: 'consonant', group: 'k-row' },
    ],
    s: [
        { char: 'サ', romaji: 'sa', type: 'consonant', group: 's-row' },
        { char: 'シ', romaji: 'shi', type: 'consonant', group: 's-row' },
        { char: 'ス', romaji: 'su', type: 'consonant', group: 's-row' },
        { char: 'セ', romaji: 'se', type: 'consonant', group: 's-row' },
        { char: 'ソ', romaji: 'so', type: 'consonant', group: 's-row' },
    ],
    t: [
        { char: 'タ', romaji: 'ta', type: 'consonant', group: 't-row' },
        { char: 'チ', romaji: 'chi', type: 'consonant', group: 't-row' },
        { char: 'ツ', romaji: 'tsu', type: 'consonant', group: 't-row' },
        { char: 'テ', romaji: 'te', type: 'consonant', group: 't-row' },
        { char: 'ト', romaji: 'to', type: 'consonant', group: 't-row' },
    ],
    n: [
        { char: 'ナ', romaji: 'na', type: 'consonant', group: 'n-row' },
        { char: 'ニ', romaji: 'ni', type: 'consonant', group: 'n-row' },
        { char: 'ヌ', romaji: 'nu', type: 'consonant', group: 'n-row' },
        { char: 'ネ', romaji: 'ne', type: 'consonant', group: 'n-row' },
        { char: 'ノ', romaji: 'no', type: 'consonant', group: 'n-row' },
    ],
    h: [
        { char: 'ハ', romaji: 'ha', type: 'consonant', group: 'h-row' },
        { char: 'ヒ', romaji: 'hi', type: 'consonant', group: 'h-row' },
        { char: 'フ', romaji: 'fu', type: 'consonant', group: 'h-row' },
        { char: 'ヘ', romaji: 'he', type: 'consonant', group: 'h-row' },
        { char: 'ホ', romaji: 'ho', type: 'consonant', group: 'h-row' },
    ],
    m: [
        { char: 'マ', romaji: 'ma', type: 'consonant', group: 'm-row' },
        { char: 'ミ', romaji: 'mi', type: 'consonant', group: 'm-row' },
        { char: 'ム', romaji: 'mu', type: 'consonant', group: 'm-row' },
        { char: 'メ', romaji: 'me', type: 'consonant', group: 'm-row' },
        { char: 'モ', romaji: 'mo', type: 'consonant', group: 'm-row' },
    ],
    y: [
        { char: 'ヤ', romaji: 'ya', type: 'consonant', group: 'y-row' },
        { char: 'ユ', romaji: 'yu', type: 'consonant', group: 'y-row' },
        { char: 'ヨ', romaji: 'yo', type: 'consonant', group: 'y-row' },
    ],
    r: [
        { char: 'ラ', romaji: 'ra', type: 'consonant', group: 'r-row' },
        { char: 'リ', romaji: 'ri', type: 'consonant', group: 'r-row' },
        { char: 'ル', romaji: 'ru', type: 'consonant', group: 'r-row' },
        { char: 'レ', romaji: 're', type: 'consonant', group: 'r-row' },
        { char: 'ロ', romaji: 'ro', type: 'consonant', group: 'r-row' },
    ],
    w: [
        { char: 'ワ', romaji: 'wa', type: 'consonant', group: 'w-row' },
        { char: 'ヲ', romaji: 'wo', type: 'consonant', group: 'w-row' },
    ],
    n: [
        { char: 'ン', romaji: 'n', type: 'special', group: 'n-special' },
    ],
    dakuten: [
        { char: 'ガ', romaji: 'ga', base: 'カ', group: 'dakuten-k' },
        { char: 'ギ', romaji: 'gi', base: 'キ', group: 'dakuten-k' },
        { char: 'グ', romaji: 'gu', base: 'ク', group: 'dakuten-k' },
        { char: 'ゲ', romaji: 'ge', base: 'ケ', group: 'dakuten-k' },
        { char: 'ゴ', romaji: 'go', base: 'コ', group: 'dakuten-k' },
        { char: 'ザ', romaji: 'za', base: 'サ', group: 'dakuten-s' },
        { char: 'ジ', romaji: 'ji', base: 'シ', group: 'dakuten-s' },
        { char: 'ズ', romaji: 'zu', base: 'ス', group: 'dakuten-s' },
        { char: 'ゼ', romaji: 'ze', base: 'セ', group: 'dakuten-s' },
        { char: 'ゾ', romaji: 'zo', base: 'ソ', group: 'dakuten-s' },
        { char: 'ダ', romaji: 'da', base: 'タ', group: 'dakuten-t' },
        { char: 'ヂ', romaji: 'ji', base: 'チ', group: 'dakuten-t' },
        { char: 'ヅ', romaji: 'zu', base: 'ツ', group: 'dakuten-t' },
        { char: 'デ', romaji: 'de', base: 'テ', group: 'dakuten-t' },
        { char: 'ド', romaji: 'do', base: 'ト', group: 'dakuten-t' },
        { char: 'バ', romaji: 'ba', base: 'ハ', group: 'dakuten-h' },
        { char: 'ビ', romaji: 'bi', base: 'ヒ', group: 'dakuten-h' },
        { char: 'ブ', romaji: 'bu', base: 'フ', group: 'dakuten-h' },
        { char: 'ベ', romaji: 'be', base: 'ヘ', group: 'dakuten-h' },
        { char: 'ボ', romaji: 'bo', base: 'ホ', group: 'dakuten-h' },
    ],
    handakuten: [
        { char: 'パ', romaji: 'pa', base: 'ハ', group: 'handakuten-h' },
        { char: 'ピ', romaji: 'pi', base: 'ヒ', group: 'handakuten-h' },
        { char: 'プ', romaji: 'pu', base: 'フ', group: 'handakuten-h' },
        { char: 'ペ', romaji: 'pe', base: 'ヘ', group: 'handakuten-h' },
        { char: 'ポ', romaji: 'po', base: 'ホ', group: 'handakuten-h' },
    ],
    combo: [
        { char: 'キャ', romaji: 'kya', base: 'キ', group: 'combo-y' },
        { char: 'キュ', romaji: 'kyu', base: 'キ', group: 'combo-y' },
        { char: 'キョ', romaji: 'kyo', base: 'キ', group: 'combo-y' },
        { char: 'シャ', romaji: 'sha', base: 'シ', group: 'combo-y' },
        { char: 'シュ', romaji: 'shu', base: 'シ', group: 'combo-y' },
        { char: 'ショ', romaji: 'sho', base: 'シ', group: 'combo-y' },
        { char: 'チャ', romaji: 'cha', base: 'チ', group: 'combo-y' },
        { char: 'チュ', romaji: 'chu', base: 'チ', group: 'combo-y' },
        { char: 'チョ', romaji: 'cho', base: 'チ', group: 'combo-y' },
        { char: 'ニャ', romaji: 'nya', base: 'ニ', group: 'combo-y' },
        { char: 'ニュ', romaji: 'nyu', base: 'ニ', group: 'combo-y' },
        { char: 'ニョ', romaji: 'nyo', base: 'ニ', group: 'combo-y' },
        { char: 'ヒャ', romaji: 'hya', base: 'ヒ', group: 'combo-y' },
        { char: 'ヒュ', romaji: 'hyu', base: 'ヒ', group: 'combo-y' },
        { char: 'ヒョ', romaji: 'hyo', base: 'ヒ', group: 'combo-y' },
        { char: 'ミャ', romaji: 'mya', base: 'ミ', group: 'combo-y' },
        { char: 'ミュ', romaji: 'myu', base: 'ミ', group: 'combo-y' },
        { char: 'ミョ', romaji: 'myo', base: 'ミ', group: 'combo-y' },
        { char: 'リャ', romaji: 'rya', base: 'リ', group: 'combo-y' },
        { char: 'リュ', romaji: 'ryu', base: 'リ', group: 'combo-y' },
        { char: 'リョ', romaji: 'ryo', base: 'リ', group: 'combo-y' },
        { char: 'ギャ', romaji: 'gya', base: 'ギ', group: 'combo-y' },
        { char: 'ギュ', romaji: 'gyu', base: 'ギ', group: 'combo-y' },
        { char: 'ギョ', romaji: 'gyo', base: 'ギ', group: 'combo-y' },
        { char: 'ジャ', romaji: 'ja', base: 'ジ', group: 'combo-y' },
        { char: 'ジュ', romaji: 'ju', base: 'ジ', group: 'combo-y' },
        { char: 'ジョ', romaji: 'jo', base: 'ジ', group: 'combo-y' },
        { char: 'ビャ', romaji: 'bya', base: 'ビ', group: 'combo-y' },
        { char: 'ビュ', romaji: 'byu', base: 'ビ', group: 'combo-y' },
        { char: 'ビョ', romaji: 'byo', base: 'ビ', group: 'combo-y' },
        { char: 'ピャ', romaji: 'pya', base: 'ピ', group: 'combo-y' },
        { char: 'ピュ', romaji: 'pyu', base: 'ピ', group: 'combo-y' },
        { char: 'ピョ', romaji: 'pyo', base: 'ピ', group: 'combo-y' },
    ],
};

// Get all hiragana/katakana as flat arrays
function getAllHiragana() {
    return Object.values(hiragana).flat();
}

function getAllKatakana() {
    return Object.values(katakana).flat();
}

// Learning structure: organized by difficulty for 30-day plan
const hiraganaLessons = [
    { day: 1, title: 'Hiragana Basics: Vowels', chars: hiragana.basic, description: 'Learn the 5 basic vowels: あいうえお' },
    { day: 2, title: 'Hiragana K-row', chars: hiragana.k, description: 'Learn かきくけこ' },
    { day: 3, title: 'Hiragana S-row', chars: hiragana.s, description: 'Learn さしすせそ' },
    { day: 4, title: 'Hiragana T-row', chars: hiragana.t, description: 'Learn たちつてと' },
    { day: 5, title: 'Hiragana N-row', chars: hiragana.n, description: 'Learn なにぬねの' },
    { day: 6, title: 'Hiragana H-row', chars: hiragana.h, description: 'Learn はひふへほ' },
    { day: 7, title: 'Hiragana Review & More', chars: [...hiragana.m, ...hiragana.y, ...hiragana.r, ...hiragana.w, ...hiragana.n], description: 'Review and learn remaining basic hiragana' },
];

const katakanaLessons = [
    { day: 8, title: 'Katakana Basics: Vowels', chars: katakana.basic, description: 'Learn the 5 basic vowels: アイウエオ' },
    { day: 9, title: 'Katakana K-row', chars: katakana.k, description: 'Learn カキクケコ' },
    { day: 10, title: 'Katakana S-row', chars: katakana.s, description: 'Learn サシスセソ' },
    { day: 11, title: 'Katakana T-row', chars: katakana.t, description: 'Learn タチツテト' },
    { day: 12, title: 'Katakana N-row', chars: katakana.n, description: 'Learn ナニヌネノ' },
    { day: 13, title: 'Katakana H-row', chars: katakana.h, description: 'Learn ハヒフヘホ' },
    { day: 14, title: 'Katakana Review & More', chars: [...katakana.m, ...katakana.y, ...katakana.r, ...katakana.w, ...katakana.n], description: 'Review and learn remaining basic katakana' },
];

module.exports = {
    hiragana,
    katakana,
    getAllHiragana,
    getAllKatakana,
    hiraganaLessons,
    katakanaLessons,
};

